### ISSUE TITLE
Number spinner

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-module-admin#1]
We should use a [spinner](http://exacttarget.github.io/fuelux/#spinner) for number (db type INT) fields in the backend. Also applying type=number wouldn't be bad except it would require targeting Chrome to either hide the spinner it puts in or use it vs FuelUX's spinner.

**Comment by daftspunk** [comment]
Suggest using the native jQuery UI spinner instead:
http://jqueryui.com/spinner/

**Comment by Garbee** [comment]
Sure, the fewer dependencies the better. Plus arrow key support!
