### ISSUE TITLE
Remove need for phprTriggerSave()

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-module-admin#4]
Currently the code editor requires us to use phprTriggerSave() like so for saving forms in the backend:

```
prepareFunction: function(){phprTriggerSave();}
```

We should just have it done by default if possible. Removing this need will reduce friction for module developers and help people make things faster!

**Comment by contextlimit** [comment]
Agree. :+1:

**Comment by daftspunk** [comment]
This is a tricky one. As far as I can tell we need to make separate helpers for delete, save and cancel buttons to streamline it.

Eg save would automatically trigger:
- WYSIWYG editor commit
- unload manager confirmation 
- control+s hot key binding 

There is definitely a need for this
